trigger:

- main



pool:

  vmImage: 'ubuntu-latest'



steps:

- task: NodeTool@0

  inputs:

    versionSpec: '17.0.1'

  displayName: 'Install Node.js'



- script: |

    npm install

  displayName: 'npm install and build'



- script: |

    npm install -g @angular/cli

  displayName: 'angular install'



- script: |

    npm install -g @ionic/cli

  displayName: 'Npm install Ionic'



- script: |

    npm install -g cordova

  displayName: 'Npm install Cordova'

  



- script: |

    ionic cordova platform add android  

  displayName: 'Generating Android Apps'



- script: |

    ionic cordova build android 

  displayName: 'Generating Android Apps'



- task: CopyFiles@2

  inputs:

    SourceFolder: '$(Agent.BuildDirectory)'

    Contents: '**/*.apk'

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

    CleanTargetFolder: true

    overWrite: false

    flattenFolders: false

    preserveTimestamp: true

  displayName: 'Copying Android App as Artifact'




- task: PublishBuildArtifacts@1

  inputs:

    pathtoPublish: '$(Build.ArtifactStagingDirectory)'

    artifactName: 'Contact'

    artifactType: 'container'